using System.Text.Json.Serialization;
using PeFix.Cli;
using PeFix.Plan;

namespace PeFix;

[JsonSerializable(typeof(PefixPlan))]
[JsonSerializable(typeof(MutationTargetJson))]
[JsonSerializable(typeof(MutationTargetJson[]))]
[JsonSerializable(typeof(SnStripJson))]
[JsonSerializable(typeof(SnStripJson[]))]
[JsonSerializable(typeof(SnBatchResultJson))]
[JsonSerializable(typeof(SnBatchResultJson[]))]
[JsonSerializable(typeof(SnBatchJson))]
[JsonSerializable(typeof(SnDepJson))]
[JsonSerializable(typeof(SnDepJson[]))]
[JsonSerializable(typeof(RedirJson))]
[JsonSerializable(typeof(RedirJson[]))]
[JsonSerializable(typeof(RedBatchJson))]
[JsonSerializable(typeof(PinvokeJson))]
[JsonSerializable(typeof(PinvokeJson[]))]
[JsonSerializable(typeof(PinBatchJson))]
[JsonSerializable(typeof(PublicJson))]
[JsonSerializable(typeof(InspectJson))]
[JsonSerializable(typeof(InspectJson[]))]
[JsonSerializable(typeof(BepInExJson))]
[JsonSerializable(typeof(BepInExPluginJson))]
[JsonSerializable(typeof(BepInExPluginJson[]))]
[JsonSerializable(typeof(BepInExDependencyJson))]
[JsonSerializable(typeof(BepInExDependencyJson[]))]
[JsonSerializable(typeof(CorFlagsJson))]
[JsonSerializable(typeof(SignalsJson))]
[JsonSerializable(typeof(AssemblyReferenceJson))]
[JsonSerializable(typeof(AssemblyReferenceJson[]))]
[JsonSerializable(typeof(ScanIssue))]
[JsonSerializable(typeof(ScanIssue[]))]
[JsonSerializable(typeof(IssueEvidence))]
[JsonSerializable(typeof(RefJson))]
[JsonSerializable(typeof(RefJson[]))]
[JsonSerializable(typeof(RefUseJson))]
[JsonSerializable(typeof(RefUseJson[]))]
[JsonSerializable(typeof(ScanGate))]
[JsonSerializable(typeof(ProfileJson))]
[JsonSerializable(typeof(FixJson))]
[JsonSerializable(typeof(RefusalJson))]
[JsonSerializable(typeof(BatchSummary))]
[JsonSerializable(typeof(ClosureJson))]
[JsonSerializable(typeof(ChainJson))]
[JsonSerializable(typeof(ChainJson[]))]
[JsonSerializable(typeof(TreeJson))]
[JsonSerializable(typeof(TreeJson[]))]
[JsonSerializable(typeof(SegmentJson))]
[JsonSerializable(typeof(SegmentJson[]))]
[JsonSerializable(typeof(BatchFixJson))]
[JsonSerializable(typeof(ScanJson))]
[JsonSerializable(typeof(RefsJson))]
[JsonSerializable(typeof(ScanSummary))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(string))]
[JsonSourceGenerationOptions(WriteIndented = true, NewLine = "\n")]
internal sealed partial class JsonContext : JsonSerializerContext
{
}
