namespace PeFix.Meta;

public readonly record struct Inspection(
    string Path,
    bool ValidPe,
    bool HasCliHeader,
    string? PeFormat,
    string? Machine,
    ManagedCorFlags ManagedCorFlags,
    Signals Signals,
    Category? Category,
    Status Status,
    string ReasonCode,
    string PrimaryCause,
    string[] RuntimeRisks,
    string[] Warnings,
    string[] NextSteps,
    string? LoadReqs,
    string[]? PInvokeDeps,
    string? Tfm,
    string? MetaVersion,
    string[]? OsPlatforms,
    AssemblyIdentity[]? AssemblyReferences,
    AssemblyIdentity? AssemblyDefinition,
    bool? HasReadyToRun = null,
    bool? IsTrimmable = null,
    BepInExMetadata? BepInEx = null);
